version: '3.4'
services:
    trinityDB:
        container_name: DbContainer
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - 8002:1433
        environment:
        - MSSQL_SA_PASSWORD=S74nkm4m1
        - ACCEPT-EULA=Y
    trinityapi:
        container_name: Trinity
        image: ${DOCKER_REGISTRY-}trinityapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - 8001:80
        depends_on:
        - DbContainer
        environment:
        - DB_HOST=trinityDB
        - DB_NAME=trinityDB
        - DB_SA_PASSWORD=S74nkm4m1


