version: '3.4'
services:
    trinityDB:
        container_name: TrinityDB
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - 8002:1433
        environment:
        - ACCEPT-EULA=Y
        - SA_PASSWORD=S74nkm4m1
    trinityapi:
        container_name: Trinity
        image: ${DOCKER_REGISTRY-}trinityapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - 8001:80
        depends_on:
        - trinityDB
        environment:
        - DB_HOST=trinityDB
        - DB_NAME=trinityDB
        - DB_SA_PASSWORD=S74nkm4m1


