version: '3.4'
networks:
    trinityNet:
services:
    DB:
        container_name: TrinityDB
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - 8001:1433
        environment:
        - SA_PASSWORD=S74nkm4m1
        - ACCEPT_EULA=Y
        networks:
        - trinityNet
    trinityapi:
        container_name: Trinity
        image: ${DOCKER_REGISTRY-}trinityapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - 80:80
        environment:
        - DB_HOST=DB
        - DB_NAME=TrinityDB
        - DB_SA_PASSWORD=S74nkm4m1
        - ASPCORE_URLS=http://+80
        networks:
        - trinityNet


