version: '3.4'
networks:
    trinityNet:
services:
    trinityDB:
        container_name: TrinityDB
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - 8002:1433
        environment:
        - MSSQL_SA_PASSWORD=S74nkm4m1
        - ACCEPT_EULA=Y
        networks:
        - trinityNet
    trinityapi:
        container_name: Trinity
        image: ${DOCKER_REGISTRY-}trinityapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - 8001:80
        environment:
        - DB_HOST=trinityDB
        - DB_NAME=Trinity
        - DB_SA_PASSWORD=S74nkm4m1
        networks:
        - trinityNet


